apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.application }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        volumeMounts:
            - name: persist-folder
              mountPath: /persist
            - name: app-settings-secrets
              mountPath: /app/appsettings-secrets.Production.json
              subPath: appsettings-secrets.Production.json
          {{- if .Values.appSettings }}
            - name: app-settings
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
          {{- end }}
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}          

      volumes:
        - name: persist-folder
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "chart.fullname" .) }}
        - name: app-settings-secrets
          secret:
            secretName: {{ include "chart.fullname" . }}-appsettings-secrets
      {{- if .Values.appSettings }}
        - name: app-settings
          configMap:
            name: {{ include "chart.fullname" . }}-appsettings
      {{- end }}

      {{- if .Values.deployment.nodeSelector -}}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end -}}

      {{- if .Values.deployment.affinity -}}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end -}}

      {{- if .Values.deployment.tolerations -}}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end -}}
